# Generated by Django 4.1.5 on 2023-01-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, verbose_name='Название города')),
                ('city_sal', models.BigIntegerField(verbose_name='Средний оклад в городе')),
                ('city_count', models.IntegerField(verbose_name='Доля вакансий от общего числа')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_name', models.CharField(max_length=50, verbose_name='Название вакансии')),
                ('vacancy_skills', models.TextField(verbose_name='Навыки')),
                ('vacancy_salary_from', models.IntegerField(verbose_name='Нижняя вилка оклада')),
                ('vacancy_salary_to', models.IntegerField(verbose_name='Верхняя вилка оклада')),
                ('vacancy_salary_currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('vacancy_area', models.CharField(max_length=30, verbose_name='Город')),
                ('vacancy_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_date', models.IntegerField(verbose_name='Год')),
                ('year_sal_all', models.BigIntegerField(verbose_name='Средний оклад в год')),
                ('year_sal_job', models.BigIntegerField(verbose_name='Средний оклад в год для профессии')),
                ('year_count_all', models.IntegerField(verbose_name='Кол-во вакансий')),
                ('year_count_job', models.IntegerField(verbose_name='Кол-во вакансий для профессии')),
            ],
        ),
    ]
