# Generated by Django 4.1.5 on 2023-01-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_count',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Доля вакансий от общего числа'),
        ),
    ]
