# Generated by Django 4.1.5 on 2023-01-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0002_alter_city_city_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_name',
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_count',
            field=models.CharField(default='Екатеринбург', max_length=30, verbose_name='Название города(доля)'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_sal',
            field=models.CharField(default='Екатеринбург', max_length=30, verbose_name='Название города(оклад)'),
        ),
    ]
