# Generated by Django 4.1.5 on 2023-01-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0004_city_count_city_sal_delete_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year_sal_all',
            field=models.BigIntegerField(verbose_name='Средний оклад в месяц'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_sal_job',
            field=models.BigIntegerField(verbose_name='Средний оклад в месяц для профессии'),
        ),
    ]
